version: "2"
services:

  builder:
    image: openlmis/dev:1
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'

  image:
    build: .
    image: openlmismz/selv-v3-extensions-config
